---
- hosts: all
  sudo: yes
  tasks:

  - name: Setup Python setuptools dependencies
    apt: pkg={{ item }} state=present
    with_items:
      - python-dev
      - python-setuptools

  - name: Bootstrap PIP using Setuptools
    easy_install: name=pip

  - name: Basic Python dependencies
    pip: name={{ item }} use_mirrors=no
    with_items:
      - virtualenv
      - virtualenvwrapper

  - name: Add virtualenvwrapper to bashrc
    lineinfile: dest=/home/vagrant/.bashrc line="source virtualenvwrapper.sh"
