---
- name: install python dev dependencies
  sudo: yes
  apt: pkg={{ item }} state=present
  with_items:
    - python-dev
    - python-setuptools

- name: bootstrap pip using setuptools
  sudo: yes
  easy_install: name=pip

- name: install virtualenv
  sudo: yes
  pip: name=virtualenv
