---
- hosts: all
  sudo: yes
  tasks:

  - name: install Python setuptools dependencies
    apt: pkg={{ item }} state=present
    with_items:
      - python-dev
      - python-setuptools

  - name: bootstrap PIP using setuptools
    easy_install: name=pip

  - name: install Python virtualenv
    pip: name=virtualenv
