---
- name: install python dev
  sudo: yes
  apt: pkg={{ item }} state=present
  with_items:
    - python-dev
    - python-setuptools

- name: install pip
  sudo: yes
  easy_install: name=pip

- name: install virtualenv
  sudo: yes
  pip: name={{ item }} state=present extra_args='--upgrade'
  with_items:
    - pip
    - virtualenv
