---
# handlers file for ansible-nginx-uwsgi-supervisor
- name: restart uwsgi app
  supervisorctl: name={{ uwsgi_app_service_name }} state=restarted config=/etc/supervisor/supervisor.conf
  sudo: yes

- name: start supervisord
  service: name=supervisor state=started
  sudo: yes

- name: start supervisord
  service: name=supervisor state=started
  sudo: yes

- name: restart supervisord
  service: name=supervisor state=restarted
  sudo: yes

- name: restart nginx
  service: name=nginx state=restarted
  sudo: yes
