---
- hosts: all
  sudo: yes
  tasks:

  # TODO Step 1 - Setup virtualenv in target
  # TODO Step 2 - Copy over package to target system
  # TODO Step 3 - PIP install into virtualenv
  # TODO Step 4 - Setup environment variables on target system related to config.
